spring.application.name=stm32-smart-disinfector-java

# Server Configuration
server.port=8090

# Application Configuration
app.device.tcp-port=9000
app.device.ack-timeout-ms=4000
app.device.offline-timeout-ms=20000

# Redis Configuration
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0

# Logging
logging.level.com.suntianyu.stm32smartdisinfectorjava=INFO
